### ISSUE TITLE
Missing module map_openbb_collection_to_langchain_tools in util.py

### ISSUE THREAD

**Issue by tinygpt** [OpenBB-finance/openbb-agents#13]
Hi team, 

I tried to rerun the jupyter notebook you shared earlier, and hit error in this line:

`from utils import map_openbb_collection_to_langchain_tools  # provides access to OpenBB Tools`

Upon checking I can't find the module under utils.py.

Is this missing?

**Comment by tinygpt** [comment]
Looks like the function was moved to another module with a different name. I tried to replace it in the notebook and it worked.

`from openbb_agents.tools import map_openbb_routes_to_langchain_tools`

**Comment by DidierRLopes** [comment]
Thank you for bringing this up - @tinygpt.

Fixed here https://github.com/OpenBB-finance/openbb-agents/pull/14
