### ISSUE TITLE
[Question] OpenBB data sources

### ISSUE THREAD

**Issue by vincentteyssier** [OpenBB-finance/openbb-agents#5]
Hi,

Very interesting notebook here.

I understand that estimates.price_target is coming from FMP data source.
Did you have the free API key only or a paying one?

I'm getting error for price_target only, quote is working fine:
openbb_core.app.model.abstract.error.OpenBBError: Error in FMP request -> unknown error

I assume that price_target is part of the advanced data from the paying API key, is that correct?

**Comment by jmaslek** [comment]
Yes.  I believe you need at least the starter plan from fmp to get that.

**Comment by vincentteyssier** [comment]
Price target is part of the Advanced Data in the premium plan, got confirmation from their sales.
Thanks, closing
